### ISSUE TITLE
A method to get all exported classes from the API

### ISSUE THREAD

**Issue by gus33000** [alien-tools/roseau#1]
Currently in roseau if one wants to get all exported types of an api, you need to call the following method: ```API api; api.getExportedTypes()```

Aside from the confusing naming of this method alongside ```getAllTypes()```, there is no method like ```getAllClasses()``` to get the exported classes of an API.

Currently if one person wants to do this, you have to write this piece of code:

```java
for (ClassDecl classDecl : mainProjectApiModel.getExportedTypes().stream()
     .filter(ClassDecl.class::isInstance)
     .map(ClassDecl.class::cast).toList()) { }
```

It would be nice to have a method like for every type to do this.

**Comment by tdegueul** [comment]
Please use https://github.com/alien-tools/roseau/blob/fdea87c21c546fe884822d4edd5324f29f84ecd6/src/main/java/com/github/maracas/roseau/api/model/API.java#L95
