### ISSUE TITLE
Document options of command line

### ISSUE THREAD

**Issue by jrfaller** [alien-tools/roseau#3]
Hello,

I have trouble understanding all the options of the command line, could there be a usage section where it is described?

Cheers!

**Comment by tdegueul** [comment]
I've set a description for the CLI options, see https://github.com/alien-tools/roseau?tab=readme-ov-file#as-a-cli-tool

**Comment by jrfaller** [comment]
LGTM, except perhaps: `--report=<reportPath> Where to write the breaking changes report; defaults to report.json`. I think it's misleading since the report seems to be written in CSV?
